[package]
name = "replace"
version = "0.1.0"
authors = ["Wesley Van Melle <van.melle.wes@gmail.com>"]
edition = "2018"
default-run = "replace"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "*"